// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID          int32
	Name        string
	Description string
	Website     string
	Email       string
	PhoneNumber string
}

type JobApplication struct {
	ID             int32
	User           int32
	JobListing     int32
	CoverLetter    pgtype.Text
	Status         string
	SentDate       pgtype.Date
	RelevantSkills []string
}

type JobListing struct {
	ID             int32
	Title          string
	Description    string
	Salary         pgtype.Numeric
	Company        int32
	DatePosted     pgtype.Date
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Location       string
	Field          string
	WorkingHours   string
	EmploymentType string
	Schedule       string
}

type User struct {
	ID          int32
	Username    string
	FirstName   string
	LastName    string
	PhoneNumber string
	Email       string
	DateOfBirth pgtype.Date
	Experience  []string
	Education   string
	Skills      []string
}

type UserFavoriteJobListing struct {
	ID         int32
	User       int32
	JobListing int32
}
