// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package database

import (
	"context"
)

const getJobListings = `-- name: GetJobListings :many
SELECT id, title, description, salary, company, date_posted, start_date, end_date, location, field, working_hours, employment_type
FROM job_listing
`

func (q *Queries) GetJobListings(ctx context.Context) ([]JobListing, error) {
	rows, err := q.db.Query(ctx, getJobListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobListing
	for rows.Next() {
		var i JobListing
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Salary,
			&i.Company,
			&i.DatePosted,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.Field,
			&i.WorkingHours,
			&i.EmploymentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
